### ISSUE TITLE
Wrapper not including spaces

### ISSUE THREAD

**Issue by ghost** [Zachoz/TelstraSMS-PHP#1]
I do not know if this is already known, but the wrapper does not seem to be including spaces in the body of the text message. I have tried with single quotation marks and with double quotation marks, but to no avail.

**Comment by zachdekoning** [comment]
Awkward. Fixed now.

It's meant to remove spaces from the "recipient" phone number. Most people give their numbers in a "XXXX XXX XXX" format and I just got lazy and wanted to remove the spaces from it. :P

**Comment by ghost** [comment]
This seemed to be fixed for a while, but it seems to be broken again. After browsing the source code, it appears that the line:
`$this->message = str_replace(" ", "", $message);`
Should be:
`$this->recipient = str_replace(" ", "", $recipient);`
As it currently removes the spaces from the message, but not the recipient, while I presume it should remove the spaces from the recipient and not the message.

EDIT:
Actually, the whole line:
`$this->recipient = $recipient;`
Can then be removed, as it is overwritten immediately by the next line.
